require('dotenv').config()
const express = require('express')
const app = express()
const cors = require('cors')
const bodyParser = require('body-parser')
const home = require('./routes/home')
const search = require('./routes/search')
const bars = require('./routes/bars')
const activities = require('./routes/activities')
const attractions = require('./routes/attractions')
const courses = require('./routes/courses')
const hotels = require('./routes/hotels')
const restaurants = require('./routes/restaurants')
const PORT = process.env.PORT || 5000

app.use(cors({ credentials: true }))
app.use(bodyParser.json())

home(app)
search(app)
bars(app)
activities(app)
attractions(app)
courses(app)
hotels(app)
restaurants(app)

app.listen(PORT, () => console.log('API is UP!! on', PORT))
